# Generated by Django 4.0.6 on 2022-08-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_regmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='postjob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jname', models.CharField(max_length=50)),
                ('cname', models.CharField(max_length=50)),
                ('extype', models.CharField(choices=[('0-1', '0-1'), ('2-3', '2-3'), ('4-5', '4-5'), ('6-7', '6-7'), ('8-9', '8-9'), ('10-11', '10-11')], max_length=100)),
                ('wptype', models.CharField(choices=[('remote', 'remote'), ('hybrid', 'hybrid')], max_length=100)),
                ('wtype', models.CharField(choices=[('fulltime', 'fulltime'), ('parttime', 'parttime')], max_length=100)),
                ('jobname', models.CharField(max_length=250)),
            ],
        ),
    ]
